name: aya_mobile
description: "Flower of the Day Flutter App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Explicitly list all your images for web deployment
  assets:
    - assets/anthurium.jpeg
    - assets/aster.jpeg
    - assets/camellia.jpeg
    - assets/dahlia.jpeg
    - assets/forget_me_not.jpeg
    - assets/gardenia.jpeg
    - assets/gerbera_daisy.jpeg
    - assets/hibiscus.jpeg
    - assets/lavender.jpeg
    - assets/plumeria.jpeg
    - assets/poppy.jpeg
    - assets/prunus_cerasifera.jpeg
    - assets/rose.jpeg
    - assets/sunflower.jpeg
    - assets/tulip.jpeg
